import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";

import { ReactScan } from "@/app/_components/react-scan-component.tsx";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "MAGIC CLEAN",
	description: "Generated by create-t3-app and fairy dust",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={geist.variable}>
			<ReactScan />
			<body>
				<SessionProvider>
					<TRPCReactProvider>{children}</TRPCReactProvider>
					<Toaster />
				</SessionProvider>
			</body>
		</html>
	);
}
