import "@/styles/globals.css";

import { SiteHeader } from "@components/app-header";
import { AppSidebar } from "@components/app-sidebar";
import { ThemeProvider } from "@components/theme-provider";
import {
	SidebarInset,
	SidebarProvider /*, SidebarTrigger*/,
} from "@components/ui/sidebar";
import { WebVitals } from "@components/web-vitals";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "sonner";

import { ReactScan } from "@/app/_components/react-scan-component.tsx";
import { TRPCReactProvider } from "@/trpc/react";
export const metadata: Metadata = {
	title: "MAGIC CLEAN",
	description: "Generated by create-t3-app and fairy dust",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={geist.variable} suppressHydrationWarning>
			<ReactScan />
			<body className="bg-background text-foreground scroll-smooth antialiased transition-colors">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					scriptProps={{ "data-cdasync": "false" }}
				>
					<TRPCReactProvider>
						<SidebarProvider>
							<AppSidebar />
							<SidebarInset>
								<SiteHeader />
								{children}
								<Toaster expand richColors />
							</SidebarInset>
						</SidebarProvider>
					</TRPCReactProvider>
					<WebVitals />
				</ThemeProvider>
			</body>
		</html>
	);
}
